#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /etc/sysconfig/heat-params
    owner: "root:root"
    permissions: "0644"
    content: |
      KUBE_API_PUBLIC_ADDRESS="$KUBE_API_PUBLIC_ADDRESS"
      KUBE_API_PRIVATE_ADDRESS="$KUBE_API_PRIVATE_ADDRESS"
      KUBE_API_PORT="$KUBE_API_PORT"
      KUBE_ALLOW_PRIV="$KUBE_ALLOW_PRIV"
      KUBE_MASTER_IPS="$KUBE_MASTER_IPS"
      KUBE_MINION_IPS="$KUBE_MINION_IPS"
      KUBE_NODE_PUBLIC_IP="$KUBE_NODE_PUBLIC_IP"
      KUBE_NODE_IP="$KUBE_NODE_IP"
      KUBE_NODE_NAME="$KUBE_NODE_NAME"
      NETWORK_DRIVER="$NETWORK_DRIVER"
      FLANNEL_NETWORK_CIDR="$FLANNEL_NETWORK_CIDR"
      FLANNEL_NETWORK_SUBNETLEN="$FLANNEL_NETWORK_SUBNETLEN"
      FLANNEL_NETWORK_SUBNET_MIN="$FLANNEL_NETWORK_SUBNET_MIN"
      FLANNEL_NETWORK_SUBNET_MAX="$FLANNEL_NETWORK_SUBNET_MAX"
      FLANNEL_BACKEND="$FLANNEL_BACKEND"
      PORTAL_NETWORK_CIDR="$PORTAL_NETWORK_CIDR"
      ETCD_DISCOVERY_URL="$ETCD_DISCOVERY_URL"
      AUTH_URL="$AUTH_URL"
      USERNAME="$USERNAME"
      PASSWORD="$PASSWORD"
      TENANT_NAME="$TENANT_NAME"
      CLUSTER_SUBNET="$CLUSTER_SUBNET"
      TLS_DISABLED="$TLS_DISABLED"
      KUBE_VERSION="$KUBE_VERSION"
      CLUSTER_UUID="$CLUSTER_UUID"
      MAGNUM_URL="$MAGNUM_URL"
      TRUSTEE_USER_ID="$TRUSTEE_USER_ID"
      TRUSTEE_PASSWORD="$TRUSTEE_PASSWORD"
      TRUST_ID="$TRUST_ID"
