heat_template_version: 2014-10-16

description: >
  This is a nested stack that defines a single Neutron port for kubernetes nodes.
  This stack is included by an AutoScalingGroup resource in the parent template
  (kubecluster.yaml).

parameters:

  security_groups:
    type: comma_delimited_list
    default: []
    description: List of the IDs security groups for kubernetes master.

  fixed_network:
    type: string
    description: Network from which to allocate fixed addresses.

  fixed_subnet:
    type: string
    description: Subnet from which to allocate fixed addresses.

resources:

  kube_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: fixed_network }
      security_groups: { get_param: security_groups }
      fixed_ips:
        - subnet: { get_param: fixed_subnet }
      replacement_policy: AUTO

outputs:

  OS::stack_id:
    value: { get_resource: kube_port }

  fixed_ip:
    value: { get_attr: [ kube_port, fixed_ips, 0, ip_address ] }
